server:
  port: 8081

spring:
  application:
    name: briseyda.arbizu

  data:
    mongodb:
      database: 01_briseyda_Arbizu
      uri: mongodb+srv://briseyda:bonitabris20@cluster0.lwskqzr.mongodb.net/?appName=Cluster0